Repository ynput/LabLib, pull requests merged in 2024-11, with the labels that each got.

#35 Bugfix/oiio write tc attribute
  lablib/renderers/slate_render.py
  tests/test_renderers_slate.py
Labels: bug

#36 Make renderers inherit from BaseRenderer.
  lablib/renderers/__init__.py
  lablib/renderers/base.py
  lablib/renderers/basic.py
  lablib/renderers/slate_render.py
  tests/test_renderers_basic.py
  tests/test_renderers_slate.py
Labels: enhancement

#37 Refactor color operators to return single OCIO Tranform object
  lablib/generators/ocio_config.py
  lablib/operators/__init__.py
  lablib/operators/color.py
  lablib/processors/ayon_hiero_effect_file.py
  lablib/processors/ayon_ociolook_file.py
  resources/public/effectPlateMain/v001/a01vfxd_sh020_effectPlateP01_v002.json
  tests/test_generators_ocio_config_file.py
  tests/test_operators_color.py
  tests/test_processors_ayon_hiero_effect_file.py
  tests/test_processors_ayon_ociolook_file.py
  tests/test_renderers_basic.py
Labels: sponsored, type: enhancement
